### ISSUE TITLE
Navigation from code of conduct & cfp

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#22]
When you go from /code-of-conduct to sponsors via the nave link, the fragment is not being picked up

<img width="929" alt="screen shot 2016-03-17 at 01 24 23" src="https://cloud.githubusercontent.com/assets/76060/13833563/0311a3a4-ebdf-11e5-9f4f-9e321068beb3.png">

**Comment by tancredi** [comment]
Fixed with a lovely bit of JS
