### ISSUE TITLE
Site performance

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#38]
Real world feedback: Took an age to load on iPhone 6+.

http://www.webpagetest.org/result/160320_DM_TVZ/

venue.png seems to take a while.

**Comment by tancredi** [comment]
Is this on old deploy? Venue photos are now all optimised jpg - We can crush most pngs on the page (There's not many there) - may look into it now

**Comment by tancredi** [comment]
Crushed the pngs - https://github.com/tancredi/nodeconf-london-2016/commit/e53e1b140373f58a82a3938dd15dae2371aa1a3d

**Comment by iancrowther** [comment]
+1
