### ISSUE TITLE
Hero - Buy Button Copy

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#4]
Can we hide this button for now and add the ticket price

£150 - Available Friday 18th March 2016 12:00GMT

**Comment by tancredi** [comment]
It's now 26th Match - we should setup ticket sale ASAP - Any news here @iancrowther ?

**Comment by iancrowther** [comment]
once speakers are agreed from the CFP, we know what the costs will be regarding flights and accommodation.  its coming!

**Comment by iancrowther** [comment]
tickets are now live
