### ISSUE TITLE
Feedback - "Very Scrolly"

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#40]
Should we consider breaking content into individual pages?

**Comment by tancredi** [comment]
We can do as we get rid of some of the initial links E.g. Call for speakers - although:

I actually think scrolling is good for this sort of info - especially while having links to the content in the header that give you a way to skip - this means you can choose to read in the order we designed (And possibly is designed to makes sense) or skip and consume however you want.

Also, a lot of conferences landing pages are a long one pager condensing most key info - I see it as an extended leaflet, and sorta makes sense for this purpose imo.

**Comment by iancrowther** [comment]
lets leave for now and enhance if/when its a thing
