### ISSUE TITLE
Event - Mention Node.js in the copy

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#46]
What do you think @orlacoding

**Comment by orlacoding** [comment]
Not sure I understand this Ian - Node.js is already mentioned in the first paragraph: "NodeConf London is a one-day, single-track conference with a laser focus on what people need to know about Node.js." And once the new target audience paragraph is added, it will be there too.

**Comment by iancrowther** [comment]
I think we were thinking broadly through the site, but the clue is in the event name and description
