### ISSUE TITLE
Lanyrd

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#50]
Postcard template from vistaprint.co.uk

[_Note_Cards-Flat-Vertical.zip](https://github.com/tancredi/nodeconf-london-2016/files/181529/_Note_Cards-Flat-Vertical.zip)

**Comment by tancredi** [comment]
Here's an idea:

![Lanyard idea preview](http://i.cubeupload.com/MyXRps.png)

**Comment by iancrowther** [comment]
ok cool, on the back we have the schedule?

**Comment by iancrowther** [comment]
will leave only put main sponsors on the sponsors list

**Comment by iancrowther** [comment]
will the names be automated for the printer

**Comment by iancrowther** [comment]
hey,

Need to get this finalised for print now

**Comment by iancrowther** [comment]
done
