### ISSUE TITLE
CSS Breakpoint off on published site

### ISSUE THREAD

**Issue by TinyExplosions** [tancredi/nodeconf-london-2016#53]
Based on the tweet at https://twitter.com/McDonnellDean/status/712270469672599557 -the publilshed version of the site has `mobile-breakpoint` set to 400px. However, in `variables.styl` is it (correctly) set to 600px, which means the referenced issue no longer happens on an iPhone 6+ sized device.

There's not really anything that needs to be changed, PR wise, I think the site just needs to be rebuilt!

**Comment by TinyExplosions** [comment]
Actually, it appears that the 400px breakpoint is one defined by griddy, not by the site, so will require a fix it seems

**Comment by tancredi** [comment]
@TinyExplosions good spot - Will fix later on today - Griddy takes a configuration variable for the mobile breakpoint, so it's just about adding parameters to the grid-system() mixin.

**Comment by tancredi** [comment]
Fixed in https://github.com/tancredi/nodeconf-london-2016/commit/2003f98f122fd09255c212868fd6692ffaa1fa3d now just needs deploying
