### ISSUE TITLE
Rendering issue in safari

### ISSUE THREAD

**Issue by TinyExplosions** [tancredi/nodeconf-london-2016#55]
There's a strange rendering issue when the site is opened in Safari on Mac (I'm on OS X 10.11.3, Safari 9.0.3). See screen shot below.
![safari](https://cloud.githubusercontent.com/assets/1452247/13999816/ff5e7870-f135-11e5-8e5f-c41ec2df538a.png)

It renders fine on Chrome on the same mac (see screenshot)
![chrome](https://cloud.githubusercontent.com/assets/1452247/13999815/ff421b1c-f135-11e5-8534-15e44b54aaaa.png)

**Comment by iancrowther** [comment]
yeah we have spotted this.  any ideas why?

**Comment by tancredi** [comment]
Fixed this in https://github.com/tancredi/nodeconf-london-2016/commit/673f6f7d763ff1f77040592cfbff57e0a86575e9 (And deployed) - Please have an extra check - although I'm quite confident closing it (Tested through browserstack on latest iSafari, where I was able to reproduce)

**Comment by TinyExplosions** [comment]
Looks great on mobile safari.

**Comment by tancredi** [comment]
Perfect. Thanks for reporting :)
