### ISSUE TITLE
Copy: Add diversity statement to landing

### ISSUE THREAD

**Issue by iancrowther** [tancredi/nodeconf-london-2016#68]
Should we add details to the event section?

'cc @orlacoding

**Comment by orlacoding** [comment]
Do we need one? The website already has a comprehensive code of conduct with credits. I suggest you run it by Des, Dean and Richard.

**Comment by iancrowther** [comment]
"Do we need one?" - this was my question too. If we are trying to find reasons to add it, then we should leave it.
