### ISSUE TITLE
Copy edit to The Event

### ISSUE THREAD

**Issue by orlacoding** [tancredi/nodeconf-london-2016#70]
Change from: 
NodeConf London is a one-day, single-track conference. 
NodeConf London will bring together our industry's enterprise heavyweights, our subject experts and highlight the finest talent London has to offer. 
We’ll bring you perspectives from the enterprise whilst providing cutting edge developer insights.

Change to: 
NodeConf London is a one-day, single-track conference with a laser focus on what people need to know about Node.js. 
It brings together the sharpest minds from the enterprise with the industry’s leading software development heavyweights and the finest talent that London has to offer.

Background: change future to present tense; bring into line with blog post.

**Comment by iancrowther** [comment]
resolved
