### ISSUE TITLE
Copy edit to Cause

### ISSUE THREAD

**Issue by orlacoding** [tancredi/nodeconf-london-2016#71]
Change from: All profits from NodeConf London 2016 will be used to support the Node.js community here in London. If you would like to waive your 'Speaker Fee', we will add it to the overall donation, and if you have an alternative charity or non-profit organization that is close to your heart, we can arrange the donation on your behalf. 
We will proudly be supporting NodeGirls, NodeBots and NodeSchool London.

Change to: Community is a key value at nearForm and we’re keeping that very much in focus for NodeConf London. Proceeds from the event are being donated to three local groups that mean a lot to everyone involved: NodeGirls, NodeBots and NodeSchool London.
What’s more, speakers can elect to donate their fee, thus generating even more cash for the causes.

Background: change future to present tense; bring into line with blog post.

**Comment by iancrowther** [comment]
resolved
