### ISSUE TITLE
Copy edit to Speakers

### ISSUE THREAD

**Issue by orlacoding** [tancredi/nodeconf-london-2016#72]
From: [Kassandra Perch] Robots, Code, and People
To: Robots, code and people

From: [Christian Heilmann] making ES6 happen with ChakraCore and Node
To: Making ES6 happen with ChakraCore and Node

From: [Emily Rose] How I Learned to Stop Worrying
To: How I learned to stop worrying

From: [Andrew Martin] Avoiding Release Paralysis
To: Avoiding release paralysis

From: [Luca Maraschi] SWIMming in the Microservices Ocean
To: SWIMming in the microservices ocean

Background: capitalization in accordance with nearForm style guide - sentence capitalization used

**Comment by iancrowther** [comment]
resolved
