### ISSUE TITLE
Copy edit to Sponsors

### ISSUE THREAD

**Issue by orlacoding** [tancredi/nodeconf-london-2016#74]
Change from: We are currently seeking sponsorship
If you want to contribute, we'd love to hear from you

Ian: are we keeping this - i.e. are we still looking for sponsorship? If so, change as follows please:

Change to:  We are currently seeking sponsorship. If you want to contribute, we’d love to hear from you.

Background: item still relevant?; full stops needed at end of sentences.

**Comment by iancrowther** [comment]
resolved
